// GENERATED CODE - DO NOT MODIFY BY HAND

part of 'nhanvien_model.dart';

// **************************************************************************
// JsonSerializableGenerator
// **************************************************************************

_$NhanVienImpl _$$NhanVienImplFromJson(Map<String, dynamic> json) =>
    _$NhanVienImpl(
      idphieu: json['idphieu'] as String?,
      ngaylap: json['ngaylap'] as String?,
      maphieu: json['maphieu'] as String?,
      idUv: json['idUv'] as String?,
      idDn: (json['idDn'] as num?)?.toInt(),
      hoten: json['hoten'] as String?,
      ngaysinh: json['ngaysinh'] as String?,
      idGioitinh: (json['idGioitinh'] as num?)?.toInt(),
      idDantoc: (json['idDantoc'] as num?)?.toInt(),
      soCmnd: json['soCmnd'] as String?,
      masoBhxh: json['masoBhxh'] as String?,
      idBacHoc: (json['idBacHoc'] as num?)?.toInt(),
      chkCnktKhongBang: json['chkCnktKhongBang'] as bool?,
      chkCcn3thang: json['chkCcn3thang'] as bool?,
      chkCcnSocap: json['chkCcnSocap'] as bool?,
      chkTrungcap: json['chkTrungcap'] as bool?,
      chkCaodang: json['chkCaodang'] as bool?,
      chkDaihocSdh: json['chkDaihocSdh'] as bool?,
      idLoaiDhld: json['idLoaiDhld'] as String?,
      ngayHdld: json['ngayHdld'] as String?,
      ngayHieuluc: json['ngayHieuluc'] as String?,
      idTinhtrangHd: (json['idTinhtrangHd'] as num?)?.toInt(),
      idChucdanh: (json['idChucdanh'] as num?)?.toInt(),
      idLoaiBh: (json['idLoaiBh'] as num?)?.toInt(),
      ngayBaohiem: json['ngayBaohiem'] as String?,
      mucluongchinh: (json['mucluongchinh'] as num?)?.toInt(),
      mucluongBhtn: (json['mucluongBhtn'] as num?)?.toInt(),
      thoigianBhtn: (json['thoigianBhtn'] as num?)?.toInt(),
      chkNhanvienmoi: json['chkNhanvienmoi'] as bool?,
      ngayBatdau: json['ngayBatdau'] as String?,
      ngayThoiviec: json['ngayThoiviec'] as String?,
      idLydoNghi: (json['idLydoNghi'] as num?)?.toInt(),
      ghichu: json['ghichu'] as String?,
      startDate: json['startDate'] == null
          ? null
          : DateTime.parse(json['startDate'] as String),
      endDate: json['endDate'] == null
          ? null
          : DateTime.parse(json['endDate'] as String),
      idphieu03: json['idphieu03'] as String?,
      status: json['status'] as bool?,
      displayOrder: (json['displayOrder'] as num?)?.toInt(),
      createdDate: json['createdDate'] as String?,
      createdBy: json['createdBy'] as String?,
      modifiredDate: json['modifiredDate'] as String?,
      modifiredBy: json['modifiredBy'] as String?,
      hoTenUv: json['hoTenUv'] as String?,
      loaiHDLD: json['loaiHDLD'] as String?,
      ngaySinhUv: json['ngaySinhUv'] as String?,
      uvGioitinh: (json['uvGioitinh'] as num?)?.toInt(),
      danTocUv: json['danTocUv'] as String?,
      dantocId: (json['dantocId'] as num?)?.toInt(),
      soCmndUv: json['soCmndUv'] as String?,
      trinhdoCm: json['trinhdoCm'] as String?,
      loaiBH: json['loaiBH'] as String?,
      tenChucdanh: json['tenChucdanh'] as String?,
      tinhtrangHd: json['tinhtrangHd'] as String?,
      tenDoanhnghiep: json['tenDoanhnghiep'] as String?,
    );

Map<String, dynamic> _$$NhanVienImplToJson(_$NhanVienImpl instance) =>
    <String, dynamic>{
      'idphieu': instance.idphieu,
      'ngaylap': instance.ngaylap,
      'maphieu': instance.maphieu,
      'idUv': instance.idUv,
      'idDn': instance.idDn,
      'hoten': instance.hoten,
      'ngaysinh': instance.ngaysinh,
      'idGioitinh': instance.idGioitinh,
      'idDantoc': instance.idDantoc,
      'soCmnd': instance.soCmnd,
      'masoBhxh': instance.masoBhxh,
      'idBacHoc': instance.idBacHoc,
      'chkCnktKhongBang': instance.chkCnktKhongBang,
      'chkCcn3thang': instance.chkCcn3thang,
      'chkCcnSocap': instance.chkCcnSocap,
      'chkTrungcap': instance.chkTrungcap,
      'chkCaodang': instance.chkCaodang,
      'chkDaihocSdh': instance.chkDaihocSdh,
      'idLoaiDhld': instance.idLoaiDhld,
      'ngayHdld': instance.ngayHdld,
      'ngayHieuluc': instance.ngayHieuluc,
      'idTinhtrangHd': instance.idTinhtrangHd,
      'idChucdanh': instance.idChucdanh,
      'idLoaiBh': instance.idLoaiBh,
      'ngayBaohiem': instance.ngayBaohiem,
      'mucluongchinh': instance.mucluongchinh,
      'mucluongBhtn': instance.mucluongBhtn,
      'thoigianBhtn': instance.thoigianBhtn,
      'chkNhanvienmoi': instance.chkNhanvienmoi,
      'ngayBatdau': instance.ngayBatdau,
      'ngayThoiviec': instance.ngayThoiviec,
      'idLydoNghi': instance.idLydoNghi,
      'ghichu': instance.ghichu,
      'startDate': instance.startDate?.toIso8601String(),
      'endDate': instance.endDate?.toIso8601String(),
      'idphieu03': instance.idphieu03,
      'status': instance.status,
      'displayOrder': instance.displayOrder,
      'createdDate': instance.createdDate,
      'createdBy': instance.createdBy,
      'modifiredDate': instance.modifiredDate,
      'modifiredBy': instance.modifiredBy,
      'hoTenUv': instance.hoTenUv,
      'loaiHDLD': instance.loaiHDLD,
      'ngaySinhUv': instance.ngaySinhUv,
      'uvGioitinh': instance.uvGioitinh,
      'danTocUv': instance.danTocUv,
      'dantocId': instance.dantocId,
      'soCmndUv': instance.soCmndUv,
      'trinhdoCm': instance.trinhdoCm,
      'loaiBH': instance.loaiBH,
      'tenChucdanh': instance.tenChucdanh,
      'tinhtrangHd': instance.tinhtrangHd,
      'tenDoanhnghiep': instance.tenDoanhnghiep,
    };
