// GENERATED CODE - DO NOT MODIFY BY HAND

part of 'm02tt11_model.dart';

// **************************************************************************
// JsonSerializableGenerator
// **************************************************************************

_$M02TT11Impl _$$M02TT11ImplFromJson(Map<String, dynamic> json) =>
    _$M02TT11Impl(
      idphieu: json['idphieu'] as String?,
      maphieu: json['maphieu'] as String?,
      ngaylap: json['ngaylap'] == null
          ? null
          : DateTime.parse(json['ngaylap'] as String),
      iduv: json['iduv'] as String?,
      hoten: json['hoten'] as String?,
      ngaysinh: json['ngaysinh'] == null
          ? null
          : DateTime.parse(json['ngaysinh'] as String),
      idGioitinh: (json['idGioitinh'] as num?)?.toInt(),
      soCmnd: json['soCmnd'] as String?,
      ngaycap: json['ngaycap'] == null
          ? null
          : DateTime.parse(json['ngaycap'] as String),
      noicap: json['noicap'] as String?,
      masoBhxh: json['masoBhxh'] as String?,
      idDantoc: (json['idDantoc'] as num?)?.toInt(),
      idTongiao: (json['idTongiao'] as num?)?.toInt(),
      idStatusVieclam: (json['idStatusVieclam'] as num?)?.toInt(),
      idDoituongCs: (json['idDoituongCs'] as num?)?.toInt(),
      idTantat: (json['idTantat'] as num?)?.toInt(),
      idTtHonNhan: const IntToBoolConverter().fromJson(json['idTtHonNhan']),
      mahoGd: json['mahoGd'] as String?,
      matinhHk: json['matinhHk'] as String?,
      mahuyenHk: json['mahuyenHk'] as String?,
      maxaHk: json['maxaHk'] as String?,
      diachiHk: json['diachiHk'] as String?,
      thonHk: json['thonHk'] as String?,
      idTinhHk: (json['idTinhHk'] as num?)?.toInt(),
      idXaHk: (json['idXaHk'] as num?)?.toInt(),
      matinhTt: json['matinhTt'] as String?,
      mahuyenTt: json['mahuyenTt'] as String?,
      maxaTt: json['maxaTt'] as String?,
      diachiTt: json['diachiTt'] as String?,
      thonTt: json['thonTt'] as String?,
      idTinhTt: (json['idTinhTt'] as num?)?.toInt(),
      idXaTt: (json['idXaTt'] as num?)?.toInt(),
      suckhoe: json['suckhoe'] as String?,
      cao: (json['cao'] as num?)?.toInt(),
      nang: (json['nang'] as num?)?.toDouble(),
      congviechientai: json['congviechientai'] as String?,
      idNguyennhanTn: (json['idNguyennhanTn'] as num?)?.toInt(),
      mucLuongTruocThatNghiep:
          (json['mucLuongTruocThatNghiep'] as num?)?.toDouble(),
      idhocvan: (json['idhocvan'] as num?)?.toInt(),
      idBacHoc: json['idBacHoc'] as String?,
      idChuyenmon: (json['idChuyenmon'] as num?)?.toInt(),
      idBacHocKhac: json['idBacHocKhac'] as String?,
      idChuyenmonKhac: (json['idChuyenmonKhac'] as num?)?.toInt(),
      trinhdok1: json['trinhdok1'] as String?,
      trinhdok2: json['trinhdok2'] as String?,
      kynangnghe: json['kynangnghe'] as String?,
      backynang: (json['backynang'] as num?)?.toInt(),
      idNndt1: (json['idNndt1'] as num?)?.toInt(),
      idTdnn1: json['idTdnn1'] as String?,
      mucNn1: (json['mucNn1'] as num?)?.toInt(),
      idNndt2: (json['idNndt2'] as num?)?.toInt(),
      idTdnn2: json['idTdnn2'] as String?,
      mucNn2: (json['mucNn2'] as num?)?.toInt(),
      idTdth: json['idTdth'] as String?,
      mucTh: (json['mucTh'] as num?)?.toInt(),
      idTdthvp: json['idTdthvp'] as String?,
      mucThvp: (json['mucThvp'] as num?)?.toInt(),
      idKynang: json['idKynang'] as String?,
      chkGt: const IntToBoolConverter().fromJson(json['chkGt']),
      chkNs: const IntToBoolConverter().fromJson(json['chkNs']),
      chkNhom: const IntToBoolConverter().fromJson(json['chkNhom']),
      chkGs: const IntToBoolConverter().fromJson(json['chkGs']),
      chkKhac: const IntToBoolConverter().fromJson(json['chkKhac']),
      chkTtr: const IntToBoolConverter().fromJson(json['chkTtr']),
      chkTh: const IntToBoolConverter().fromJson(json['chkTh']),
      chkDl: const IntToBoolConverter().fromJson(json['chkDl']),
      chkPb: const IntToBoolConverter().fromJson(json['chkPb']),
      chkQltg: const IntToBoolConverter().fromJson(json['chkQltg']),
      chkTu: const IntToBoolConverter().fromJson(json['chkTu']),
      chkApl: const IntToBoolConverter().fromJson(json['chkApl']),
      kynangkhac: json['kynangkhac'] as String?,
      khanangNoitroi: json['khanangNoitroi'] as String?,
      kinhnghiemLv: json['kinhnghiemLv'] as String?,
      lvNuocngoai: const IntToBoolConverter().fromJson(json['lvNuocngoai']),
      lvNuocngoaitai: json['lvNuocngoaitai'] as String?,
      idLhdn: json['idLhdn'] as String?,
      tenVv: json['tenVv'] as String?,
      motaCv: json['motaCv'] as String?,
      nganhId: (json['nganhId'] as num?)?.toInt(),
      level1: (json['level1'] as num?)?.toInt(),
      level2: (json['level2'] as num?)?.toInt(),
      level3: (json['level3'] as num?)?.toInt(),
      level4: (json['level4'] as num?)?.toInt(),
      idChucvu: (json['idChucvu'] as num?)?.toInt(),
      idKinhnghiem: json['idKinhnghiem'] as String?,
      noiLvTinh1: json['noiLvTinh1'] as String?,
      noiLvkcn1: (json['noiLvkcn1'] as num?)?.toInt(),
      noiLvTinh2: json['noiLvTinh2'] as String?,
      noiLvkcn2: (json['noiLvkcn2'] as num?)?.toInt(),
      idLoaiDhld: json['idLoaiDhld'] as String?,
      idCalamviec: (json['idCalamviec'] as num?)?.toInt(),
      idHinhthuc: json['idHinhthuc'] as String?,
      idMucdich: json['idMucdich'] as String?,
      idMucluong: (json['idMucluong'] as num?)?.toInt(),
      dieukienlamviec: json['dieukienlamviec'] as String?,
      chkPl01: const IntToBoolConverter().fromJson(json['chkPl01']),
      chkPl02: const IntToBoolConverter().fromJson(json['chkPl02']),
      chkPl03: const IntToBoolConverter().fromJson(json['chkPl03']),
      chkPl04: const IntToBoolConverter().fromJson(json['chkPl04']),
      tienPhucloi: (json['tienPhucloi'] as num?)?.toInt(),
      chkPl05: const IntToBoolConverter().fromJson(json['chkPl05']),
      chkPl06: const IntToBoolConverter().fromJson(json['chkPl06']),
      chkPl07: const IntToBoolConverter().fromJson(json['chkPl07']),
      chkPl08: const IntToBoolConverter().fromJson(json['chkPl08']),
      chkPl09: const IntToBoolConverter().fromJson(json['chkPl09']),
      chkPl10: const IntToBoolConverter().fromJson(json['chkPl10']),
      chkPl11: const IntToBoolConverter().fromJson(json['chkPl11']),
      chkPl12: const IntToBoolConverter().fromJson(json['chkPl12']),
      chkPl13: const IntToBoolConverter().fromJson(json['chkPl13']),
      chkPl14: const IntToBoolConverter().fromJson(json['chkPl14']),
      chkPl15: const IntToBoolConverter().fromJson(json['chkPl15']),
      chkPl16: const IntToBoolConverter().fromJson(json['chkPl16']),
      chkPl17: const IntToBoolConverter().fromJson(json['chkPl17']),
      phucloikhac: json['phucloikhac'] as String?,
      chkNl1: const IntToBoolConverter().fromJson(json['chkNl1']),
      chkNl2: const IntToBoolConverter().fromJson(json['chkNl2']),
      chkNl3: const IntToBoolConverter().fromJson(json['chkNl3']),
      chkTl1: const IntToBoolConverter().fromJson(json['chkTl1']),
      chkTl2: const IntToBoolConverter().fromJson(json['chkTl2']),
      chkTl3: const IntToBoolConverter().fromJson(json['chkTl3']),
      chkDl1: const IntToBoolConverter().fromJson(json['chkDl1']),
      chkDl2: const IntToBoolConverter().fromJson(json['chkDl2']),
      chkDl3: const IntToBoolConverter().fromJson(json['chkDl3']),
      chkNn1: const IntToBoolConverter().fromJson(json['chkNn1']),
      chkNn2: const IntToBoolConverter().fromJson(json['chkNn2']),
      chkNn3: const IntToBoolConverter().fromJson(json['chkNn3']),
      chkY01: const IntToBoolConverter().fromJson(json['chkY01']),
      chkY02: const IntToBoolConverter().fromJson(json['chkY02']),
      chkTy1: const IntToBoolConverter().fromJson(json['chkTy1']),
      chkTy2: const IntToBoolConverter().fromJson(json['chkTy2']),
      chkTy3: const IntToBoolConverter().fromJson(json['chkTy3']),
      chk2T1: const IntToBoolConverter().fromJson(json['chk2T1']),
      chk2T2: const IntToBoolConverter().fromJson(json['chk2T2']),
      chk2T3: const IntToBoolConverter().fromJson(json['chk2T3']),
      chk2T4: const IntToBoolConverter().fromJson(json['chk2T4']),
      chk2T5: const IntToBoolConverter().fromJson(json['chk2T5']),
      sslv1: const IntToBoolConverter().fromJson(json['sslv1']),
      sslv2: const IntToBoolConverter().fromJson(json['sslv2']),
      chkTuvanCs: const IntToBoolConverter().fromJson(json['chkTuvanCs']),
      chkTuvanVl: const IntToBoolConverter().fromJson(json['chkTuvanVl']),
      chkTuvanDt: const IntToBoolConverter().fromJson(json['chkTuvanDt']),
      chkTuvanBhtn: const IntToBoolConverter().fromJson(json['chkTuvanBhtn']),
      chkTuvankhac: const IntToBoolConverter().fromJson(json['chkTuvankhac']),
      dKyKhac: json['dKyKhac'] as String?,
      idHinhthucTd: json['idHinhthucTd'] as String?,
      tenLienhe: json['tenLienhe'] as String?,
      dienthoai: json['dienthoai'] as String?,
      email: json['email'] as String?,
      nhanSms: const IntToBoolConverter().fromJson(json['nhanSms']),
      nhanEMail: const IntToBoolConverter().fromJson(json['nhanEMail']),
      hinhthuckhac: json['hinhthuckhac'] as String?,
      lienHeTimViec: json['lienHeTimViec'] as String?,
      urlFile: json['urlFile'] as String?,
      idNguonThuThap: json['idNguonThuThap'] as String?,
      idVetinh: json['idVetinh'] as String?,
      tenNguoiViet: json['tenNguoiViet'] as String?,
      displayOrder: (json['displayOrder'] as num?)?.toInt(),
      status: const IntToBoolConverter().fromJson(json['status']),
    );

Map<String, dynamic> _$$M02TT11ImplToJson(_$M02TT11Impl instance) =>
    <String, dynamic>{
      'idphieu': instance.idphieu,
      'maphieu': instance.maphieu,
      'ngaylap': instance.ngaylap?.toIso8601String(),
      'iduv': instance.iduv,
      'hoten': instance.hoten,
      'ngaysinh': instance.ngaysinh?.toIso8601String(),
      'idGioitinh': instance.idGioitinh,
      'soCmnd': instance.soCmnd,
      'ngaycap': instance.ngaycap?.toIso8601String(),
      'noicap': instance.noicap,
      'masoBhxh': instance.masoBhxh,
      'idDantoc': instance.idDantoc,
      'idTongiao': instance.idTongiao,
      'idStatusVieclam': instance.idStatusVieclam,
      'idDoituongCs': instance.idDoituongCs,
      'idTantat': instance.idTantat,
      'idTtHonNhan': const IntToBoolConverter().toJson(instance.idTtHonNhan),
      'mahoGd': instance.mahoGd,
      'matinhHk': instance.matinhHk,
      'mahuyenHk': instance.mahuyenHk,
      'maxaHk': instance.maxaHk,
      'diachiHk': instance.diachiHk,
      'thonHk': instance.thonHk,
      'idTinhHk': instance.idTinhHk,
      'idXaHk': instance.idXaHk,
      'matinhTt': instance.matinhTt,
      'mahuyenTt': instance.mahuyenTt,
      'maxaTt': instance.maxaTt,
      'diachiTt': instance.diachiTt,
      'thonTt': instance.thonTt,
      'idTinhTt': instance.idTinhTt,
      'idXaTt': instance.idXaTt,
      'suckhoe': instance.suckhoe,
      'cao': instance.cao,
      'nang': instance.nang,
      'congviechientai': instance.congviechientai,
      'idNguyennhanTn': instance.idNguyennhanTn,
      'mucLuongTruocThatNghiep': instance.mucLuongTruocThatNghiep,
      'idhocvan': instance.idhocvan,
      'idBacHoc': instance.idBacHoc,
      'idChuyenmon': instance.idChuyenmon,
      'idBacHocKhac': instance.idBacHocKhac,
      'idChuyenmonKhac': instance.idChuyenmonKhac,
      'trinhdok1': instance.trinhdok1,
      'trinhdok2': instance.trinhdok2,
      'kynangnghe': instance.kynangnghe,
      'backynang': instance.backynang,
      'idNndt1': instance.idNndt1,
      'idTdnn1': instance.idTdnn1,
      'mucNn1': instance.mucNn1,
      'idNndt2': instance.idNndt2,
      'idTdnn2': instance.idTdnn2,
      'mucNn2': instance.mucNn2,
      'idTdth': instance.idTdth,
      'mucTh': instance.mucTh,
      'idTdthvp': instance.idTdthvp,
      'mucThvp': instance.mucThvp,
      'idKynang': instance.idKynang,
      'chkGt': const IntToBoolConverter().toJson(instance.chkGt),
      'chkNs': const IntToBoolConverter().toJson(instance.chkNs),
      'chkNhom': const IntToBoolConverter().toJson(instance.chkNhom),
      'chkGs': const IntToBoolConverter().toJson(instance.chkGs),
      'chkKhac': const IntToBoolConverter().toJson(instance.chkKhac),
      'chkTtr': const IntToBoolConverter().toJson(instance.chkTtr),
      'chkTh': const IntToBoolConverter().toJson(instance.chkTh),
      'chkDl': const IntToBoolConverter().toJson(instance.chkDl),
      'chkPb': const IntToBoolConverter().toJson(instance.chkPb),
      'chkQltg': const IntToBoolConverter().toJson(instance.chkQltg),
      'chkTu': const IntToBoolConverter().toJson(instance.chkTu),
      'chkApl': const IntToBoolConverter().toJson(instance.chkApl),
      'kynangkhac': instance.kynangkhac,
      'khanangNoitroi': instance.khanangNoitroi,
      'kinhnghiemLv': instance.kinhnghiemLv,
      'lvNuocngoai': const IntToBoolConverter().toJson(instance.lvNuocngoai),
      'lvNuocngoaitai': instance.lvNuocngoaitai,
      'idLhdn': instance.idLhdn,
      'tenVv': instance.tenVv,
      'motaCv': instance.motaCv,
      'nganhId': instance.nganhId,
      'level1': instance.level1,
      'level2': instance.level2,
      'level3': instance.level3,
      'level4': instance.level4,
      'idChucvu': instance.idChucvu,
      'idKinhnghiem': instance.idKinhnghiem,
      'noiLvTinh1': instance.noiLvTinh1,
      'noiLvkcn1': instance.noiLvkcn1,
      'noiLvTinh2': instance.noiLvTinh2,
      'noiLvkcn2': instance.noiLvkcn2,
      'idLoaiDhld': instance.idLoaiDhld,
      'idCalamviec': instance.idCalamviec,
      'idHinhthuc': instance.idHinhthuc,
      'idMucdich': instance.idMucdich,
      'idMucluong': instance.idMucluong,
      'dieukienlamviec': instance.dieukienlamviec,
      'chkPl01': const IntToBoolConverter().toJson(instance.chkPl01),
      'chkPl02': const IntToBoolConverter().toJson(instance.chkPl02),
      'chkPl03': const IntToBoolConverter().toJson(instance.chkPl03),
      'chkPl04': const IntToBoolConverter().toJson(instance.chkPl04),
      'tienPhucloi': instance.tienPhucloi,
      'chkPl05': const IntToBoolConverter().toJson(instance.chkPl05),
      'chkPl06': const IntToBoolConverter().toJson(instance.chkPl06),
      'chkPl07': const IntToBoolConverter().toJson(instance.chkPl07),
      'chkPl08': const IntToBoolConverter().toJson(instance.chkPl08),
      'chkPl09': const IntToBoolConverter().toJson(instance.chkPl09),
      'chkPl10': const IntToBoolConverter().toJson(instance.chkPl10),
      'chkPl11': const IntToBoolConverter().toJson(instance.chkPl11),
      'chkPl12': const IntToBoolConverter().toJson(instance.chkPl12),
      'chkPl13': const IntToBoolConverter().toJson(instance.chkPl13),
      'chkPl14': const IntToBoolConverter().toJson(instance.chkPl14),
      'chkPl15': const IntToBoolConverter().toJson(instance.chkPl15),
      'chkPl16': const IntToBoolConverter().toJson(instance.chkPl16),
      'chkPl17': const IntToBoolConverter().toJson(instance.chkPl17),
      'phucloikhac': instance.phucloikhac,
      'chkNl1': const IntToBoolConverter().toJson(instance.chkNl1),
      'chkNl2': const IntToBoolConverter().toJson(instance.chkNl2),
      'chkNl3': const IntToBoolConverter().toJson(instance.chkNl3),
      'chkTl1': const IntToBoolConverter().toJson(instance.chkTl1),
      'chkTl2': const IntToBoolConverter().toJson(instance.chkTl2),
      'chkTl3': const IntToBoolConverter().toJson(instance.chkTl3),
      'chkDl1': const IntToBoolConverter().toJson(instance.chkDl1),
      'chkDl2': const IntToBoolConverter().toJson(instance.chkDl2),
      'chkDl3': const IntToBoolConverter().toJson(instance.chkDl3),
      'chkNn1': const IntToBoolConverter().toJson(instance.chkNn1),
      'chkNn2': const IntToBoolConverter().toJson(instance.chkNn2),
      'chkNn3': const IntToBoolConverter().toJson(instance.chkNn3),
      'chkY01': const IntToBoolConverter().toJson(instance.chkY01),
      'chkY02': const IntToBoolConverter().toJson(instance.chkY02),
      'chkTy1': const IntToBoolConverter().toJson(instance.chkTy1),
      'chkTy2': const IntToBoolConverter().toJson(instance.chkTy2),
      'chkTy3': const IntToBoolConverter().toJson(instance.chkTy3),
      'chk2T1': const IntToBoolConverter().toJson(instance.chk2T1),
      'chk2T2': const IntToBoolConverter().toJson(instance.chk2T2),
      'chk2T3': const IntToBoolConverter().toJson(instance.chk2T3),
      'chk2T4': const IntToBoolConverter().toJson(instance.chk2T4),
      'chk2T5': const IntToBoolConverter().toJson(instance.chk2T5),
      'sslv1': const IntToBoolConverter().toJson(instance.sslv1),
      'sslv2': const IntToBoolConverter().toJson(instance.sslv2),
      'chkTuvanCs': const IntToBoolConverter().toJson(instance.chkTuvanCs),
      'chkTuvanVl': const IntToBoolConverter().toJson(instance.chkTuvanVl),
      'chkTuvanDt': const IntToBoolConverter().toJson(instance.chkTuvanDt),
      'chkTuvanBhtn': const IntToBoolConverter().toJson(instance.chkTuvanBhtn),
      'chkTuvankhac': const IntToBoolConverter().toJson(instance.chkTuvankhac),
      'dKyKhac': instance.dKyKhac,
      'idHinhthucTd': instance.idHinhthucTd,
      'tenLienhe': instance.tenLienhe,
      'dienthoai': instance.dienthoai,
      'email': instance.email,
      'nhanSms': const IntToBoolConverter().toJson(instance.nhanSms),
      'nhanEMail': const IntToBoolConverter().toJson(instance.nhanEMail),
      'hinhthuckhac': instance.hinhthuckhac,
      'lienHeTimViec': instance.lienHeTimViec,
      'urlFile': instance.urlFile,
      'idNguonThuThap': instance.idNguonThuThap,
      'idVetinh': instance.idVetinh,
      'tenNguoiViet': instance.tenNguoiViet,
      'displayOrder': instance.displayOrder,
      'status': const IntToBoolConverter().toJson(instance.status),
    };
