// GENERATED CODE - DO NOT MODIFY BY HAND

part of 'ld.dart';

// **************************************************************************
// JsonSerializableGenerator
// **************************************************************************

LdModel _$LdModelFromJson(Map<String, dynamic> json) => LdModel(
      idphieu: (json['Idphieu'] as num).toInt(),
      maphieu: json['Maphieu'] as String,
      ngaylap: DateTime.parse(json['Ngaylap'] as String),
      iduv: (json['Iduv'] as num).toInt(),
      hoten: json['Hoten'] as String,
      ngaysinh: json['Ngaysinh'] == null
          ? null
          : DateTime.parse(json['Ngaysinh'] as String),
      idGioitinh: (json['IdGioitinh'] as num).toInt(),
      soCMND: json['SoCMND'] as String?,
      masoBHXH: json['MasoBHXH'] as String?,
      idDantoc: (json['IdDantoc'] as num?)?.toInt(),
      idTongiao: (json['IdTongiao'] as num?)?.toInt(),
      matinhHK: json['MatinhHK'] as String,
      mahuyenHK: json['MahuyenHK'] as String,
      maxaHK: json['MaxaHK'] as String,
      diachiHK: json['DiachiHK'] as String?,
      matinhTT: json['MatinhTT'] as String,
      mahuyenTT: json['MahuyenTT'] as String,
      maxaTT: json['MaxaTT'] as String,
      diachiTT: json['DiachiTT'] as String?,
      iddoituong: (json['Iddoituong'] as num).toInt(),
      chkTantat: json['chkTantat'] as bool?,
      idTantat: (json['IdTantat'] as num?)?.toInt(),
      chkHongheo: json['chkHongheo'] as bool?,
      chkHocanngheo: json['chkHocanngheo'] as bool?,
      thuhoidat: json['Thuhoidat'] as bool?,
      cocongcm: json['Cocongcm'] as bool?,
      dantocts: json['Dantocts'] as bool?,
      idDantocts: (json['IdDantocts'] as num?)?.toInt(),
      idhocvan: (json['Idhocvan'] as num?)?.toInt(),
      idBacHoc: json['IdBacHoc'] as String?,
      idChuyennganh: json['IdChuyennganh'] as String?,
      idNganh: (json['IdNganh'] as num?)?.toInt(),
      chkCovieclam: json['chkCovieclam'] as bool?,
      chkThatnghiep: json['chkThatnghiep'] as bool?,
      chkKhongthamgia: json['chkKhongthamgia'] as bool?,
      chkDihoc: json['chkDihoc'] as bool?,
      chkHuutri: json['chkHuutri'] as bool?,
      chkNoitro: json['chkNoitro'] as bool?,
      chkKhuyettat: json['chkKhuyettat'] as bool?,
      chkKhac: json['chkKhac'] as bool?,
      idVithevieclam: (json['IdVithevieclam'] as num?)?.toInt(),
      viecdanglam: json['Viecdanglam'] as String,
      idLoaiBH: (json['IdLoaiBH'] as num?)?.toInt(),
      chkHopdongLD: json['chkHopdongLD'] as bool?,
      idLoaiHD: json['IdLoaiHD'] as String?,
      thoigianHD: json['ThoigianHD'] == null
          ? null
          : DateTime.parse(json['ThoigianHD'] as String),
      noilamviec: json['Noilamviec'] as String?,
      idLoaiHinhNoilamviec: (json['IdLoaiHinhNoilamviec'] as num?)?.toInt(),
      idLoaihinhDN: json['IdLoaihinhDN'] as String?,
      diachiNoilamviec: json['DiachiNoilamviec'] as String?,
      idLoaithatnghiep: (json['IdLoaithatnghiep'] as num?)?.toInt(),
      idTGThatnghiep: (json['IdTGThatnghiep'] as num?)?.toInt(),
      ghichu: json['Ghichu'] as String?,
      tenNguoiViet: json['TenNguoiViet'] as String?,
      dienthoai: json['Dienthoai'] as String?,
      email: json['Email'] as String?,
      displayOrder: (json['DisplayOrder'] as num).toInt(),
      createdDate: DateTime.parse(json['CreatedDate'] as String),
      createdBy: json['CreatedBy'] as String?,
      modifiredDate: DateTime.parse(json['ModifiredDate'] as String),
      modifiredBy: json['ModifiredBy'] as String?,
      mahoGD: json['MahoGD'] as String?,
      status: json['Status'] as bool,
    );

Map<String, dynamic> _$LdModelToJson(LdModel instance) => <String, dynamic>{
      'Idphieu': instance.idphieu,
      'Maphieu': instance.maphieu,
      'Ngaylap': instance.ngaylap.toIso8601String(),
      'Iduv': instance.iduv,
      'Hoten': instance.hoten,
      'Ngaysinh': instance.ngaysinh?.toIso8601String(),
      'IdGioitinh': instance.idGioitinh,
      'SoCMND': instance.soCMND,
      'MasoBHXH': instance.masoBHXH,
      'IdDantoc': instance.idDantoc,
      'IdTongiao': instance.idTongiao,
      'MatinhHK': instance.matinhHK,
      'MahuyenHK': instance.mahuyenHK,
      'MaxaHK': instance.maxaHK,
      'DiachiHK': instance.diachiHK,
      'MatinhTT': instance.matinhTT,
      'MahuyenTT': instance.mahuyenTT,
      'MaxaTT': instance.maxaTT,
      'DiachiTT': instance.diachiTT,
      'Iddoituong': instance.iddoituong,
      'chkTantat': instance.chkTantat,
      'IdTantat': instance.idTantat,
      'chkHongheo': instance.chkHongheo,
      'chkHocanngheo': instance.chkHocanngheo,
      'Thuhoidat': instance.thuhoidat,
      'Cocongcm': instance.cocongcm,
      'Dantocts': instance.dantocts,
      'IdDantocts': instance.idDantocts,
      'Idhocvan': instance.idhocvan,
      'IdBacHoc': instance.idBacHoc,
      'IdChuyennganh': instance.idChuyennganh,
      'IdNganh': instance.idNganh,
      'chkCovieclam': instance.chkCovieclam,
      'chkThatnghiep': instance.chkThatnghiep,
      'chkKhongthamgia': instance.chkKhongthamgia,
      'chkDihoc': instance.chkDihoc,
      'chkHuutri': instance.chkHuutri,
      'chkNoitro': instance.chkNoitro,
      'chkKhuyettat': instance.chkKhuyettat,
      'chkKhac': instance.chkKhac,
      'IdVithevieclam': instance.idVithevieclam,
      'Viecdanglam': instance.viecdanglam,
      'IdLoaiBH': instance.idLoaiBH,
      'chkHopdongLD': instance.chkHopdongLD,
      'IdLoaiHD': instance.idLoaiHD,
      'ThoigianHD': instance.thoigianHD?.toIso8601String(),
      'Noilamviec': instance.noilamviec,
      'IdLoaiHinhNoilamviec': instance.idLoaiHinhNoilamviec,
      'IdLoaihinhDN': instance.idLoaihinhDN,
      'DiachiNoilamviec': instance.diachiNoilamviec,
      'IdLoaithatnghiep': instance.idLoaithatnghiep,
      'IdTGThatnghiep': instance.idTGThatnghiep,
      'Ghichu': instance.ghichu,
      'TenNguoiViet': instance.tenNguoiViet,
      'Dienthoai': instance.dienthoai,
      'Email': instance.email,
      'DisplayOrder': instance.displayOrder,
      'CreatedDate': instance.createdDate.toIso8601String(),
      'CreatedBy': instance.createdBy,
      'ModifiredDate': instance.modifiredDate.toIso8601String(),
      'ModifiredBy': instance.modifiredBy,
      'MahoGD': instance.mahoGD,
      'Status': instance.status,
    };
