import 'package:freezed_annotation/freezed_annotation.dart';

part 'tblNhaTuyenDung_model.freezed.dart';
part 'tblNhaTuyenDung_model.g.dart';

@freezed
class NtdModel with _$NtdModel {
  const factory NtdModel({
    String? idDoanhNghiep,
    String? username,
    String? password,
    String? ntdMadn,
    String? ntdTentat,
    String? ntdTen,
    String? imagePath,
    String? mst,
    int? ntdHinhThucDoanhNghiep,
    int? ntdSoLaoDong,
    String? ntdGioiThieu,
    int? ntdKdnId,
    int? ntdThuockhucongnghiep,
    String? ntdDiaChiThanhPho,
    String? ntdDiaChiHuyen,
    String? ntdDiaChiXaPhuong,
    String? ntdDiaChiChiTiet,
    String? ntdNguoiLienHe,
    int? ntdChucvu,
    String? ntdDienThoai,
    String? ntdFax,
    String? ntdEmail,
    String? ntdWebsite,
    @Default(false) bool ntdDuyet,
    @Default(false) bool ntdTopBlock,
    String? ntdQuocgia,
    int? ntdNamthanhlap,
    String? ntdLinhvuchoatdong,
    @Default(false) bool ntdhtNlh,
    @Default(false) bool ntdhtTelephone,
    @Default(false) bool ntdhtWeb,
    @Default(false) bool ntdhtFax,
    @Default(false) bool ntdhtEmail,
    @Default(false) bool ntdhtAddress,
    @Default('system') String? createdBy,
    @Default('system') String? modifiredBy,
    required DateTime? createdDate,
    required DateTime? modifiredDate,
    String? ntdId,
    @Default(false) bool newsletterSubscription,
    @Default(false) bool jobsletterSubscription,
    int? ntdLoai,
    String? nongThonThanhThi,
    String? idLoaiHinhDoanhNghiep,
    String? idNganhKinhTe,
    int? idThoiGianHoatDong,
    int? idStatus,
    int? displayOrder,
    String? ntdTenTinh,
    String? ntdTenHuyen,
    String? ntdTenXa,
    int? idnongThonThanhThi,
    String? idQuocGia,
  }) = _NtdModel;

  factory NtdModel.fromJson(Map<String, dynamic> json) => NtdModel(
        idDoanhNghiep: json['idDoanhNghiep']?.toString(),
        username: json['username'] as String?,
        password: json['password'] as String?,
        ntdMadn: json['ntdMadn'] as String?,
        ntdTentat: json['ntdTentat'] as String?,
        ntdTen: json['ntdTen'] as String?,
        imagePath: json['imagePath'] as String?,
        mst: json['mst'] as String?,
        ntdHinhThucDoanhNghiep: json['ntdHinhThucDoanhNghiep'] as int?,
        ntdSoLaoDong: json['ntdSoLaoDong'] as int?,
        ntdGioiThieu: json['ntdGioithieu'] as String?,
        ntdKdnId: json['ntdKdnId'] as int?,
        ntdThuockhucongnghiep: json['ntdThuockhucongnghiep'] as int?,
        ntdDiaChiThanhPho: json['ntdDiachithanhpho'] as String?,
        ntdDiaChiHuyen: json['ntdDiachihuyen'] as String?,
        ntdDiaChiXaPhuong: json['ntdDiachixaphuong'] as String?,
        ntdDiaChiChiTiet: json['ntdDiachichitiet'] as String?,
        ntdNguoiLienHe: json['ntdNguoilienhe'] as String?,
        ntdChucvu: json['ntdChucvu'] as int?,
        ntdDienThoai: json['ntdDienthoai'] as String?,
        ntdFax: json['ntdFax'] as String?,
        ntdEmail: json['ntdEmail'] as String?,
        ntdWebsite: json['ntdWebsite'] as String?,
        ntdDuyet: json['ntdDuyet'] as bool? ?? false,
        ntdTopBlock: json['ntdTopblock'] as bool? ?? false,
        ntdQuocgia: json['ntdQuocgia'] as String?,
        ntdNamthanhlap: json['ntdNamthanhlap'] as int?,
        ntdLinhvuchoatdong: json['ntdLinhvuchoatdong'] as String?,
        ntdhtNlh: json['ntdhtNlh'] as bool? ?? false,
        ntdhtTelephone: json['ntdhtTelephone'] as bool? ?? false,
        ntdhtWeb: json['ntdhtWeb'] as bool? ?? false,
        ntdhtFax: json['ntdhtFax'] as bool? ?? false,
        ntdhtEmail: json['ntdhtEmail'] as bool? ?? false,
        ntdhtAddress: json['ntdhtAddress'] as bool? ?? false,
        createdBy: json['createdBy'] as String? ?? 'system',
        modifiredBy: json['modifiredBy'] as String? ?? 'system',
        createdDate: json['createdDate'] == null
            ? null
            : DateTime.tryParse(json['createdDate'] as String),
        modifiredDate: json['modifiredDate'] == null
            ? null
            : DateTime.tryParse(json['modifiredDate'] as String),
        ntdId: json['ntdId'] as String?,
        newsletterSubscription:
            json['newsletterSubscription'] as bool? ?? false,
        jobsletterSubscription:
            json['jobsletterSubscription'] as bool? ?? false,
        ntdLoai: json['ntdLoai'] as int?,
        nongThonThanhThi: json['nongThonThanhThi'] as String?,
        idLoaiHinhDoanhNghiep: json['idLoaiHinhDoanhNghiep'] as String?,
        idNganhKinhTe: json['idNganhKinhTe'] as String?,
        idThoiGianHoatDong: json['idThoiGianHoatDong'] as int?,
        idStatus: json['idStatus'] as int?,
        displayOrder: json['displayOrder'] as int?,
        ntdTenTinh: json['ntdTenTinh'] as String?,
        ntdTenHuyen: json['ntdTenHuyen'] as String?,
        ntdTenXa: json['ntdTenXa'] as String?,
        idnongThonThanhThi: json['idnongThonThanhThi'] as int?,
        idQuocGia: json['idQuocGia'] as String?,
      );
}
