import 'package:freezed_annotation/freezed_annotation.dart';

part 'tblNhaTuyenDung_model.freezed.dart';
part 'tblNhaTuyenDung_model.g.dart';

@freezed
class Ntd with _$Ntd {
  factory Ntd({
    String? idDoanhNghiep,
    String? username,
    String? password,
    String? ntdMadn,
    String? ntdTentat,
    // required String ntdTen,
    String? ntdTen,
    String? imagePath,
    // required String mst,
    String? mst,
    int? ntdSolaodong,
    String? ntdGioithieu,
    // required int ntdThuockhucongnghiep,
    dynamic ntdThuockhucongnghiep,
    dynamic ntdDiachithanhpho,
    String? ntdDiachihuyen,
    String? ntdDiachixaphuong,
    String? ntdDiachichitiet,
    String? ntdNguoilienhe,
    // required int ntdChucvu,
    dynamic ntdChucvu,
    String? ntdDienthoai,
    String? ntdFax,
    // required String ntdEmail,
    String? ntdEmail,
    String? ntdWebsite,
    bool? ntdDuyet,
    bool? ntdTopblock,
    String? ntdQuocgia,
    int? ntdNamthanhlap,
    String? ntdLinhvuchoatdong,
    bool? ntdhtNlh,
    bool? ntdhtTelephone,
    bool? ntdhtWeb,
    bool? ntdhtFax,
    bool? ntdhtEmail,
    bool? ntdhtAddress,
    DateTime? createdDate,
    String? createdBy,
    DateTime? modifiredDate,
    String? modifiredBy,
    String? ntdId,
    bool? newsletterSubscription,
    bool? jobsletterSubscription,
    int? ntdLoai,
    String? nongThonThanhThi,
    String? idLoaiHinhDoanhNghiep,
    int? ntdHinhthucdoanhnghiep,
    String? idNganhKinhTe,
    int? idThoiGianHoatDong,
    // required int idStatus,
    int? idStatus,
    // required int displayOrder,
    int? displayOrder,
    String? ntdTenTinh,
    String? ntdTenHuyen,
    String? ntdTenXa,
    // required int idnongThonThanhThi,
    int? idnongThonThanhThi,
    int? idQuocGia,
  }) = _Ntd;

  factory Ntd.fromJson(Map<String, dynamic> json) => _$NtdFromJson(json);
}
