// GENERATED CODE - DO NOT MODIFY BY HAND

part of 'tblNhaTuyenDung_model.dart';

// **************************************************************************
// JsonSerializableGenerator
// **************************************************************************

_$NtdImpl _$$NtdImplFromJson(Map<String, dynamic> json) => _$NtdImpl(
      idDoanhNghiep: json['idDoanhNghiep'] as String?,
      username: json['username'] as String?,
      password: json['password'] as String?,
      ntdMadn: json['ntdMadn'] as String?,
      ntdTentat: json['ntdTentat'] as String?,
      ntdTen: json['ntdTen'] as String?,
      imagePath: json['imagePath'] as String?,
      mst: json['mst'] as String?,
      ntdSolaodong: (json['ntdSolaodong'] as num?)?.toInt(),
      ntdGioithieu: json['ntdGioithieu'] as String?,
      ntdThuockhucongnghiep: (json['ntdThuockhucongnghiep'] as num?)?.toInt(),
      ntdDiachithanhpho: json['ntdDiachithanhpho'] as String?,
      ntdDiachihuyen: json['ntdDiachihuyen'] as String?,
      ntdDiachixaphuong: json['ntdDiachixaphuong'] as String?,
      ntdDiachichitiet: json['ntdDiachichitiet'] as String?,
      ntdNguoilienhe: json['ntdNguoilienhe'] as String?,
      ntdChucvu: (json['ntdChucvu'] as num?)?.toInt(),
      ntdDienthoai: json['ntdDienthoai'] as String?,
      ntdFax: json['ntdFax'] as String?,
      ntdEmail: json['ntdEmail'] as String?,
      ntdWebsite: json['ntdWebsite'] as String?,
      ntdDuyet: json['ntdDuyet'] as bool?,
      ntdTopblock: json['ntdTopblock'] as bool?,
      ntdQuocgia: json['ntdQuocgia'] as String?,
      ntdNamthanhlap: (json['ntdNamthanhlap'] as num?)?.toInt(),
      ntdLinhvuchoatdong: json['ntdLinhvuchoatdong'] as String?,
      ntdhtNlh: json['ntdhtNlh'] as bool?,
      ntdhtTelephone: json['ntdhtTelephone'] as bool?,
      ntdhtWeb: json['ntdhtWeb'] as bool?,
      ntdhtFax: json['ntdhtFax'] as bool?,
      ntdhtEmail: json['ntdhtEmail'] as bool?,
      ntdhtAddress: json['ntdhtAddress'] as bool?,
      createdDate: json['createdDate'] == null
          ? null
          : DateTime.parse(json['createdDate'] as String),
      createdBy: json['createdBy'] as String?,
      modifiredDate: json['modifiredDate'] == null
          ? null
          : DateTime.parse(json['modifiredDate'] as String),
      modifiredBy: json['modifiredBy'] as String?,
      ntdId: json['ntdId'] as String?,
      newsletterSubscription: json['newsletterSubscription'] as bool?,
      jobsletterSubscription: json['jobsletterSubscription'] as bool?,
      ntdLoai: (json['ntdLoai'] as num?)?.toInt(),
      nongThonThanhThi: json['nongThonThanhThi'] as String?,
      idLoaiHinhDoanhNghiep: json['idLoaiHinhDoanhNghiep'] as String?,
      ntdHinhthucdoanhnghiep: (json['ntdHinhthucdoanhnghiep'] as num?)?.toInt(),
      idNganhKinhTe: json['idNganhKinhTe'] as String?,
      idThoiGianHoatDong: (json['idThoiGianHoatDong'] as num?)?.toInt(),
      idStatus: (json['idStatus'] as num?)?.toInt(),
      displayOrder: (json['displayOrder'] as num?)?.toInt(),
      ntdTenTinh: json['ntdTenTinh'] as String?,
      ntdTenHuyen: json['ntdTenHuyen'] as String?,
      ntdTenXa: json['ntdTenXa'] as String?,
      idnongThonThanhThi: (json['idnongThonThanhThi'] as num?)?.toInt(),
      idQuocGia: (json['idQuocGia'] as num?)?.toInt(),
    );

Map<String, dynamic> _$$NtdImplToJson(_$NtdImpl instance) => <String, dynamic>{
      'idDoanhNghiep': instance.idDoanhNghiep,
      'username': instance.username,
      'password': instance.password,
      'ntdMadn': instance.ntdMadn,
      'ntdTentat': instance.ntdTentat,
      'ntdTen': instance.ntdTen,
      'imagePath': instance.imagePath,
      'mst': instance.mst,
      'ntdSolaodong': instance.ntdSolaodong,
      'ntdGioithieu': instance.ntdGioithieu,
      'ntdThuockhucongnghiep': instance.ntdThuockhucongnghiep,
      'ntdDiachithanhpho': instance.ntdDiachithanhpho,
      'ntdDiachihuyen': instance.ntdDiachihuyen,
      'ntdDiachixaphuong': instance.ntdDiachixaphuong,
      'ntdDiachichitiet': instance.ntdDiachichitiet,
      'ntdNguoilienhe': instance.ntdNguoilienhe,
      'ntdChucvu': instance.ntdChucvu,
      'ntdDienthoai': instance.ntdDienthoai,
      'ntdFax': instance.ntdFax,
      'ntdEmail': instance.ntdEmail,
      'ntdWebsite': instance.ntdWebsite,
      'ntdDuyet': instance.ntdDuyet,
      'ntdTopblock': instance.ntdTopblock,
      'ntdQuocgia': instance.ntdQuocgia,
      'ntdNamthanhlap': instance.ntdNamthanhlap,
      'ntdLinhvuchoatdong': instance.ntdLinhvuchoatdong,
      'ntdhtNlh': instance.ntdhtNlh,
      'ntdhtTelephone': instance.ntdhtTelephone,
      'ntdhtWeb': instance.ntdhtWeb,
      'ntdhtFax': instance.ntdhtFax,
      'ntdhtEmail': instance.ntdhtEmail,
      'ntdhtAddress': instance.ntdhtAddress,
      'createdDate': instance.createdDate?.toIso8601String(),
      'createdBy': instance.createdBy,
      'modifiredDate': instance.modifiredDate?.toIso8601String(),
      'modifiredBy': instance.modifiredBy,
      'ntdId': instance.ntdId,
      'newsletterSubscription': instance.newsletterSubscription,
      'jobsletterSubscription': instance.jobsletterSubscription,
      'ntdLoai': instance.ntdLoai,
      'nongThonThanhThi': instance.nongThonThanhThi,
      'idLoaiHinhDoanhNghiep': instance.idLoaiHinhDoanhNghiep,
      'ntdHinhthucdoanhnghiep': instance.ntdHinhthucdoanhnghiep,
      'idNganhKinhTe': instance.idNganhKinhTe,
      'idThoiGianHoatDong': instance.idThoiGianHoatDong,
      'idStatus': instance.idStatus,
      'displayOrder': instance.displayOrder,
      'ntdTenTinh': instance.ntdTenTinh,
      'ntdTenHuyen': instance.ntdTenHuyen,
      'ntdTenXa': instance.ntdTenXa,
      'idnongThonThanhThi': instance.idnongThonThanhThi,
      'idQuocGia': instance.idQuocGia,
    };
