import 'package:freezed_annotation/freezed_annotation.dart';

part 'tblNhaTuyenDung_model.freezed.dart';
part 'tblNhaTuyenDung_model.g.dart';

@freezed
class Ntd with _$Ntd {
  factory Ntd({
    String? idDoanhNghiep,
    String? username,
    String? password,
    String? ntdMadn,
    String? ntdTentat,
    // required String ntdTen,
    String? ntdTen,
    String? imagePath,
    // required String mst,
    String? mst,
    int? ntdSolaodong,
    String? ntdGioithieu,
    // required int ntdThuockhucongnghiep,
    int? ntdThuockhucongnghiep,
    String? ntdDiachithanhpho,
    String? ntdDiachihuyen,
    String? ntdDiachixaphuong,
    String? ntdDiachichitiet,
    String? ntdNguoilienhe,
    // required int ntdChucvu,
    int? ntdChucvu,
    String? ntdDienthoai,
    String? ntdFax,
    // required String ntdEmail,
    String? ntdEmail,
    String? ntdWebsite,
    // required bool ntdDuyet,
    // required bool ntdTopblock,
    bool? ntdDuyet,
    bool? ntdTopblock,
    String? ntdQuocgia,
    int? ntdNamthanhlap,
    String? ntdLinhvuchoatdong,
    // required bool ntdhtNlh,
    // required bool ntdhtTelephone,
    // required bool ntdhtWeb,
    // required bool ntdhtFax,
    // required bool ntdhtEmail,
    // required bool ntdhtAddress,
    // required DateTime createdDate,
    bool? ntdhtNlh,
    bool? ntdhtTelephone,
    bool? ntdhtWeb,
    bool? ntdhtFax,
    bool? ntdhtEmail,
    bool? ntdhtAddress,
    DateTime? createdDate,
    // required String createdBy,
    String? createdBy,
    // required DateTime modifiredDate,
    DateTime? modifiredDate,
    // required String modifiredBy,
    String? modifiredBy,
    String? ntdId,
    // required bool newsletterSubscription,
    // required bool jobsletterSubscription,
    bool? newsletterSubscription,
    bool? jobsletterSubscription,
    // required int ntdLoai,
    int? ntdLoai,
    String? nongThonThanhThi,
    int? idLoaiHinhDoanhNghiep,
    int? ntdHinhthucdoanhnghiep,
    int? idNganhKinhTe,
    int? idThoiGianHoatDong,
    // required int idStatus,
    int? idStatus,
    // required int displayOrder,
    int? displayOrder,
    String? ntdTenTinh,
    String? ntdTenHuyen,
    String? ntdTenXa,
    // required int idnongThonThanhThi,
    int? idnongThonThanhThi,
    int? idQuocGia,
  }) = _Ntd;

  factory Ntd.fromJson(Map<String, dynamic> json) => _$NtdFromJson(json);
}
