// GENERATED CODE - DO NOT MODIFY BY HAND

part of 'tblNhaTuyenDung_model.dart';

// **************************************************************************
// JsonSerializableGenerator
// **************************************************************************

_$NtdModelImpl _$$NtdModelImplFromJson(Map<String, dynamic> json) =>
    _$NtdModelImpl(
      idDoanhNghiep: (json['idDoanhNghiep'] as num).toInt(),
      username: json['username'] as String?,
      password: json['password'] as String?,
      ntdMadn: json['ntdMadn'] as String,
      ntdTentat: json['ntdTentat'] as String?,
      ntdTen: json['ntdTen'] as String?,
      imagePath: json['imagePath'] as String?,
      mst: json['mst'] as String?,
      ntdHinhThucDoanhNghiep: (json['ntdHinhThucDoanhNghiep'] as num?)?.toInt(),
      ntdSoLaoDong: (json['ntdSoLaoDong'] as num?)?.toInt(),
      ntdGioiThieu: json['ntdGioiThieu'] as String?,
      ntdKdnId: (json['ntdKdnId'] as num?)?.toInt(),
      ntdThuocKhuCongNghiep: json['ntdThuocKhuCongNghiep'] as String?,
      ntdDiaChiThanhPho: (json['ntdDiaChiThanhPho'] as num?)?.toInt(),
      ntdDiaChiHuyen: json['ntdDiaChiHuyen'] as String?,
      ntdDiaChiXaPhuong: json['ntdDiaChiXaPhuong'] as String?,
      ntdDiaChiChiTiet: json['ntdDiaChiChiTiet'] as String?,
      ntdNguoiLienHe: json['ntdNguoiLienHe'] as String?,
      ntdChucVu: json['ntdChucVu'] as String?,
      ntdDienThoai: json['ntdDienThoai'] as String?,
      ntdFax: json['ntdFax'] as String?,
      ntdEmail: json['ntdEmail'] as String?,
      ntdWebsite: json['ntdWebsite'] as String?,
      ntdDuyet: json['ntdDuyet'] as bool? ?? false,
      ntdTopBlock: json['ntdTopBlock'] as bool? ?? false,
      ntdQuocGia: json['ntdQuocGia'] as String?,
      ntdNamThanhLap: (json['ntdNamThanhLap'] as num?)?.toInt(),
      ntdLinhVucHoatDong: json['ntdLinhVucHoatDong'] as String?,
      ntdhtNlh: json['ntdhtNlh'] as bool? ?? false,
      ntdhtTelephone: json['ntdhtTelephone'] as bool? ?? false,
      ntdhtWeb: json['ntdhtWeb'] as bool? ?? false,
      ntdhtFax: json['ntdhtFax'] as bool? ?? false,
      ntdhtEmail: json['ntdhtEmail'] as bool? ?? false,
      ntdhtAddress: json['ntdhtAddress'] as bool? ?? false,
      createdBy: json['createdBy'] as String? ?? 'system',
      modifiredBy: json['modifiredBy'] as String? ?? 'system',
      createdDate: DateTime.parse(json['createdDate'] as String),
      modifiredDate: DateTime.parse(json['modifiredDate'] as String),
      ntdId: json['ntdId'] as String?,
      newsletterSubscription: json['newsletterSubscription'] as bool? ?? false,
      jobsletterSubscription: json['jobsletterSubscription'] as bool? ?? false,
      ntdLoai: (json['ntdLoai'] as num?)?.toInt(),
      nongThonThanhThi: json['nongThonThanhThi'] as String?,
      idLoaiHinhDoanhNghiep: json['idLoaiHinhDoanhNghiep'] as String?,
      idNganhKinhTe: json['idNganhKinhTe'] as String?,
      idThoiGianHoatDong: (json['idThoiGianHoatDong'] as num?)?.toInt(),
      idStatus: (json['idStatus'] as num).toInt(),
      displayOrder: (json['displayOrder'] as num).toInt(),
    );

Map<String, dynamic> _$$NtdModelImplToJson(_$NtdModelImpl instance) =>
    <String, dynamic>{
      'idDoanhNghiep': instance.idDoanhNghiep,
      'username': instance.username,
      'password': instance.password,
      'ntdMadn': instance.ntdMadn,
      'ntdTentat': instance.ntdTentat,
      'ntdTen': instance.ntdTen,
      'imagePath': instance.imagePath,
      'mst': instance.mst,
      'ntdHinhThucDoanhNghiep': instance.ntdHinhThucDoanhNghiep,
      'ntdSoLaoDong': instance.ntdSoLaoDong,
      'ntdGioiThieu': instance.ntdGioiThieu,
      'ntdKdnId': instance.ntdKdnId,
      'ntdThuocKhuCongNghiep': instance.ntdThuocKhuCongNghiep,
      'ntdDiaChiThanhPho': instance.ntdDiaChiThanhPho,
      'ntdDiaChiHuyen': instance.ntdDiaChiHuyen,
      'ntdDiaChiXaPhuong': instance.ntdDiaChiXaPhuong,
      'ntdDiaChiChiTiet': instance.ntdDiaChiChiTiet,
      'ntdNguoiLienHe': instance.ntdNguoiLienHe,
      'ntdChucVu': instance.ntdChucVu,
      'ntdDienThoai': instance.ntdDienThoai,
      'ntdFax': instance.ntdFax,
      'ntdEmail': instance.ntdEmail,
      'ntdWebsite': instance.ntdWebsite,
      'ntdDuyet': instance.ntdDuyet,
      'ntdTopBlock': instance.ntdTopBlock,
      'ntdQuocGia': instance.ntdQuocGia,
      'ntdNamThanhLap': instance.ntdNamThanhLap,
      'ntdLinhVucHoatDong': instance.ntdLinhVucHoatDong,
      'ntdhtNlh': instance.ntdhtNlh,
      'ntdhtTelephone': instance.ntdhtTelephone,
      'ntdhtWeb': instance.ntdhtWeb,
      'ntdhtFax': instance.ntdhtFax,
      'ntdhtEmail': instance.ntdhtEmail,
      'ntdhtAddress': instance.ntdhtAddress,
      'createdBy': instance.createdBy,
      'modifiredBy': instance.modifiredBy,
      'createdDate': instance.createdDate.toIso8601String(),
      'modifiredDate': instance.modifiredDate.toIso8601String(),
      'ntdId': instance.ntdId,
      'newsletterSubscription': instance.newsletterSubscription,
      'jobsletterSubscription': instance.jobsletterSubscription,
      'ntdLoai': instance.ntdLoai,
      'nongThonThanhThi': instance.nongThonThanhThi,
      'idLoaiHinhDoanhNghiep': instance.idLoaiHinhDoanhNghiep,
      'idNganhKinhTe': instance.idNganhKinhTe,
      'idThoiGianHoatDong': instance.idThoiGianHoatDong,
      'idStatus': instance.idStatus,
      'displayOrder': instance.displayOrder,
    };
