import 'package:freezed_annotation/freezed_annotation.dart';

part 'tblHoSoUngVien_model.freezed.dart';
part 'tblHoSoUngVien_model.g.dart';

@freezed
class TblHoSoUngVienModel with _$TblHoSoUngVienModel {
  const factory TblHoSoUngVienModel({
    required String id, // Changed to String
    String? uvUsername,
    String? uvPassword,
    String? uvHoten,
    String? uvEmail,
    String? maHoSo,
    int? idDanToc,
    String? cvMongMuon,
    String? documentPath,
    String? imagePath,
    String? uvDiachichitiet,
    String? uvDienthoai,
    String? uvSoCMND,
    DateTime? uvNgaycap,
    String? uvNoicap,
    int? uvGioitinh,
    String? uvChieucao,
    String? uvCannang,
    DateTime? uvNgaysinh,
    String? uvcmCongviechientai,
    String? uvnvNganhnghe,
    String? uvnvNoilamviec,
    int? idMucluong,
    double? uvnvTienluong,
    String? uvGhichu,
    String? uvcmBangcap,
    String? uvcmKynang,
    String? uvcmTrinhdongoaingu,
    String? uvcmTrinhdotinhoc,
    @Default(0) int? uvcmKinhnghiem,
    @Default(0) int? uvSolanxem,
    @Default(0) int? interview,
    @Default(0) int? interviewed,
    @Default(false) bool? uvDuyet,
    @Default(false) bool? uvHienthi,
    @Default(false) bool? uvhtTelephone,
    @Default(false) bool? uvhtEmail,
    @Default(false) bool? uvhtAddress,
    DateTime? createdDate,
    String? createdBy,
    DateTime? modifiredDate,
    String? modifiredBy,
    String? uvId,
    @Default(false) bool? newsletterSubscription,
    @Default(false) bool? jobsletterSubscription,
    bool? coBHTN,
    String? soNhaDuong,
    int? idThanhPho,
    String? idTinh,
    String? idHuyen,
    String? idXa,
    String? idTv, // Changed to String?
    String? mahoGD,
    String? fileCV,
    int? displayOrder,
    DateTime? ngayduyet,
    String? idNguonThuThap,
    String? avatarUrl,
    String? idBacHoc,
    String? diachilienhe,
    int? uvnvNganhngheId,
    int? uvcmTrinhdoId,
    int? uvDoituongchinhsachId,
    int? uvnvThoigianId,
    int? uvnvVitrimongmuonid,
    @Default(false) bool? uvHonnhanId,
    String? tenDanToc,
    int? uvTinhtrangtantatId,
    int? uvnvHinhthuccongtyId,
  }) = _TblHoSoUngVienModel;

  factory TblHoSoUngVienModel.fromJson(Map<String, dynamic> json) =>
      _$TblHoSoUngVienModelFromJson(json);
}
