import 'package:freezed_annotation/freezed_annotation.dart';

part 'tblHoSoUngVien_model.freezed.dart';
part 'tblHoSoUngVien_model.g.dart';

@freezed
class TblHoSoUngVienModel with _$TblHoSoUngVienModel {
  const factory TblHoSoUngVienModel({
    required String id,
    String? uvUsername,
    String? uvPassword,
    String? uvHoten,
    String? uvEmail,
    String? maHoSo,
    String? tenDanToc,
    int? idDanToc,
    String? cvMongMuon,
    String? documentPath,
    String? imagePath,
    String? uvDiachichitiet,
    String? uvDienthoai,
    String? uvSoCmnd,
    String? uvNgaycap,
    String? uvNoicap,
    int? uvGioitinh,
    String? uvChieucao,
    String? uvCannang,
    String? uvDoituongchinhsach,
    int? uvDoituongchinhsachId,
    String? uvTinhtrangtantat,
    int? uvTinhtrangtantatId,
    String? uvHonnhan,
    @Default(false) bool? uvHonnhanId,
    String? uvNgaysinh,
    String? uvcmCongviechientai,
    String? uvnvNganhnghe,
    int? uvnvNganhngheId,
    String? uvnvVitrimongmuon,
    int? uvnvVitrimongmuonid,
    String? uvnvThoigian,
    int? uvnvThoigianId,
    String? uvnvNoilamviec,
    int? idMucluong,
    double? uvnvTienluong,
    String? uvnvHinhthuccongty,
    int? uvnvHinhthuccongtyId,
    String? uvGhichu,
    String? uvcmTrinhdo,
    int? uvcmTrinhdoId,
    String? uvcmBangcap,
    String? uvcmKynang,
    String? uvcmTrinhdongoaingu,
    String? uvcmTrinhdotinhoc,
    @Default(0) int? uvcmKinhnghiem,
    @Default(0) int? uvSolanxem,
    @Default(0) int? interview,
    @Default(0) int? interviewed,
    @Default(false) bool? uvDuyet,
    @Default(false) bool? uvHienthi,
    @Default(false) bool? uvhtTelephone,
    @Default(false) bool? uvhtEmail,
    @Default(false) bool? uvhtAddress,
    String? uvId,
    @Default(false) bool? newsletterSubscription,
    @Default(false) bool? jobsletterSubscription,
    bool? coBhtn,
    String? soNhaDuong,
    int? idThanhPho,
    String? idTinh,
    String? idhuyen,
    String? idxa,
    String? idtv,
    String? mahoGd,
    dynamic fileCv,
    int? displayOrder,
    DateTime? ngayduyet,
    String? idNguonThuThap,
    dynamic avatarUrl,
    dynamic avatar,
    String? idBacHoc,
    String? diachilienhe,
  }) = _TblHoSoUngVienModel;

  factory TblHoSoUngVienModel.fromJson(Map<String, dynamic> json) =>
      _$TblHoSoUngVienModelFromJson(json);
}
