// GENERATED CODE - DO NOT MODIFY BY HAND

part of 'tblHoSoUngVien_model.dart';

// **************************************************************************
// JsonSerializableGenerator
// **************************************************************************

_$TblHoSoUngVienModelImpl _$$TblHoSoUngVienModelImplFromJson(
        Map<String, dynamic> json) =>
    _$TblHoSoUngVienModelImpl(
      id: json['id'] as String,
      uvUsername: json['uvUsername'] as String?,
      uvPassword: json['uvPassword'] as String?,
      uvHoten: json['uvHoten'] as String?,
      uvEmail: json['uvEmail'] as String?,
      maHoSo: json['maHoSo'] as String?,
      tenDanToc: json['tenDanToc'] as String?,
      idDanToc: (json['idDanToc'] as num?)?.toInt(),
      cvMongMuon: json['cvMongMuon'] as String?,
      documentPath: json['documentPath'] as String?,
      imagePath: json['imagePath'] as String?,
      uvDiachichitiet: json['uvDiachichitiet'] as String?,
      uvDienthoai: json['uvDienthoai'] as String?,
      uvSoCmnd: json['uvSoCmnd'] as String?,
      uvNgaycap: json['uvNgaycap'] as String?,
      uvNoicap: json['uvNoicap'] as String?,
      uvGioitinh: (json['uvGioitinh'] as num?)?.toInt(),
      uvChieucao: json['uvChieucao'] as String?,
      uvCannang: json['uvCannang'] as String?,
      uvDoituongchinhsach: json['uvDoituongchinhsach'] as String?,
      uvDoituongchinhsachId: (json['uvDoituongchinhsachId'] as num?)?.toInt(),
      uvTinhtrangtantat: json['uvTinhtrangtantat'] as String?,
      uvTinhtrangtantatId: (json['uvTinhtrangtantatId'] as num?)?.toInt(),
      uvHonnhan: json['uvHonnhan'] as String?,
      uvHonnhanId: json['uvHonnhanId'] as bool? ?? false,
      uvNgaysinh: json['uvNgaysinh'] as String?,
      uvcmCongviechientai: json['uvcmCongviechientai'] as String?,
      uvnvNganhnghe: json['uvnvNganhnghe'] as String?,
      uvnvNganhngheId: (json['uvnvNganhngheId'] as num?)?.toInt(),
      uvnvVitrimongmuon: json['uvnvVitrimongmuon'] as String?,
      uvnvVitrimongmuonid: (json['uvnvVitrimongmuonid'] as num?)?.toInt(),
      uvnvThoigian: json['uvnvThoigian'] as String?,
      uvnvThoigianId: (json['uvnvThoigianId'] as num?)?.toInt(),
      uvnvNoilamviec: json['uvnvNoilamviec'] as String?,
      idMucluong: (json['idMucluong'] as num?)?.toInt(),
      uvnvTienluong: (json['uvnvTienluong'] as num?)?.toDouble(),
      uvnvHinhthuccongty: json['uvnvHinhthuccongty'] as String?,
      uvnvHinhthuccongtyId: (json['uvnvHinhthuccongtyId'] as num?)?.toInt(),
      uvGhichu: json['uvGhichu'] as String?,
      uvcmTrinhdo: json['uvcmTrinhdo'] as String?,
      uvcmTrinhdoId: (json['uvcmTrinhdoId'] as num?)?.toInt(),
      uvcmBangcap: json['uvcmBangcap'] as String?,
      uvcmKynang: json['uvcmKynang'] as String?,
      uvcmTrinhdongoaingu: json['uvcmTrinhdongoaingu'] as String?,
      uvcmTrinhdotinhoc: json['uvcmTrinhdotinhoc'] as String?,
      uvcmKinhnghiem: (json['uvcmKinhnghiem'] as num?)?.toInt() ?? 0,
      uvSolanxem: (json['uvSolanxem'] as num?)?.toInt() ?? 0,
      interview: (json['interview'] as num?)?.toInt() ?? 0,
      interviewed: (json['interviewed'] as num?)?.toInt() ?? 0,
      uvDuyet: json['uvDuyet'] as bool? ?? false,
      uvHienthi: json['uvHienthi'] as bool? ?? false,
      uvhtTelephone: json['uvhtTelephone'] as bool? ?? false,
      uvhtEmail: json['uvhtEmail'] as bool? ?? false,
      uvhtAddress: json['uvhtAddress'] as bool? ?? false,
      uvId: json['uvId'] as String?,
      newsletterSubscription: json['newsletterSubscription'] as bool? ?? false,
      jobsletterSubscription: json['jobsletterSubscription'] as bool? ?? false,
      coBhtn: json['coBhtn'] as bool?,
      soNhaDuong: json['soNhaDuong'] as String?,
      idThanhPho: (json['idThanhPho'] as num?)?.toInt(),
      idTinh: json['idTinh'] as String?,
      idhuyen: json['idhuyen'] as String?,
      idxa: json['idxa'] as String?,
      idTinhMoi: (json['idTinhMoi'] as num?)?.toInt(),
      idxaMoi: (json['idxaMoi'] as num?)?.toInt(),
      idtv: json['idtv'] as String?,
      mahoGd: json['mahoGd'] as String?,
      fileCv: json['fileCv'],
      displayOrder: (json['displayOrder'] as num?)?.toInt(),
      ngayduyet: json['ngayduyet'] == null
          ? null
          : DateTime.parse(json['ngayduyet'] as String),
      idNguonThuThap: json['idNguonThuThap'] as String?,
      avatarUrl: json['avatarUrl'],
      avatar: json['avatar'],
      idBacHoc: json['idBacHoc'] as String?,
      diachilienhe: json['diachilienhe'] as String?,
    );

Map<String, dynamic> _$$TblHoSoUngVienModelImplToJson(
        _$TblHoSoUngVienModelImpl instance) =>
    <String, dynamic>{
      'id': instance.id,
      'uvUsername': instance.uvUsername,
      'uvPassword': instance.uvPassword,
      'uvHoten': instance.uvHoten,
      'uvEmail': instance.uvEmail,
      'maHoSo': instance.maHoSo,
      'tenDanToc': instance.tenDanToc,
      'idDanToc': instance.idDanToc,
      'cvMongMuon': instance.cvMongMuon,
      'documentPath': instance.documentPath,
      'imagePath': instance.imagePath,
      'uvDiachichitiet': instance.uvDiachichitiet,
      'uvDienthoai': instance.uvDienthoai,
      'uvSoCmnd': instance.uvSoCmnd,
      'uvNgaycap': instance.uvNgaycap,
      'uvNoicap': instance.uvNoicap,
      'uvGioitinh': instance.uvGioitinh,
      'uvChieucao': instance.uvChieucao,
      'uvCannang': instance.uvCannang,
      'uvDoituongchinhsach': instance.uvDoituongchinhsach,
      'uvDoituongchinhsachId': instance.uvDoituongchinhsachId,
      'uvTinhtrangtantat': instance.uvTinhtrangtantat,
      'uvTinhtrangtantatId': instance.uvTinhtrangtantatId,
      'uvHonnhan': instance.uvHonnhan,
      'uvHonnhanId': instance.uvHonnhanId,
      'uvNgaysinh': instance.uvNgaysinh,
      'uvcmCongviechientai': instance.uvcmCongviechientai,
      'uvnvNganhnghe': instance.uvnvNganhnghe,
      'uvnvNganhngheId': instance.uvnvNganhngheId,
      'uvnvVitrimongmuon': instance.uvnvVitrimongmuon,
      'uvnvVitrimongmuonid': instance.uvnvVitrimongmuonid,
      'uvnvThoigian': instance.uvnvThoigian,
      'uvnvThoigianId': instance.uvnvThoigianId,
      'uvnvNoilamviec': instance.uvnvNoilamviec,
      'idMucluong': instance.idMucluong,
      'uvnvTienluong': instance.uvnvTienluong,
      'uvnvHinhthuccongty': instance.uvnvHinhthuccongty,
      'uvnvHinhthuccongtyId': instance.uvnvHinhthuccongtyId,
      'uvGhichu': instance.uvGhichu,
      'uvcmTrinhdo': instance.uvcmTrinhdo,
      'uvcmTrinhdoId': instance.uvcmTrinhdoId,
      'uvcmBangcap': instance.uvcmBangcap,
      'uvcmKynang': instance.uvcmKynang,
      'uvcmTrinhdongoaingu': instance.uvcmTrinhdongoaingu,
      'uvcmTrinhdotinhoc': instance.uvcmTrinhdotinhoc,
      'uvcmKinhnghiem': instance.uvcmKinhnghiem,
      'uvSolanxem': instance.uvSolanxem,
      'interview': instance.interview,
      'interviewed': instance.interviewed,
      'uvDuyet': instance.uvDuyet,
      'uvHienthi': instance.uvHienthi,
      'uvhtTelephone': instance.uvhtTelephone,
      'uvhtEmail': instance.uvhtEmail,
      'uvhtAddress': instance.uvhtAddress,
      'uvId': instance.uvId,
      'newsletterSubscription': instance.newsletterSubscription,
      'jobsletterSubscription': instance.jobsletterSubscription,
      'coBhtn': instance.coBhtn,
      'soNhaDuong': instance.soNhaDuong,
      'idThanhPho': instance.idThanhPho,
      'idTinh': instance.idTinh,
      'idhuyen': instance.idhuyen,
      'idxa': instance.idxa,
      'idTinhMoi': instance.idTinhMoi,
      'idxaMoi': instance.idxaMoi,
      'idtv': instance.idtv,
      'mahoGd': instance.mahoGd,
      'fileCv': instance.fileCv,
      'displayOrder': instance.displayOrder,
      'ngayduyet': instance.ngayduyet?.toIso8601String(),
      'idNguonThuThap': instance.idNguonThuThap,
      'avatarUrl': instance.avatarUrl,
      'avatar': instance.avatar,
      'idBacHoc': instance.idBacHoc,
      'diachilienhe': instance.diachilienhe,
    };
