// GENERATED CODE - DO NOT MODIFY BY HAND

part of 'sgdvl_model.dart';

// **************************************************************************
// JsonSerializableGenerator
// **************************************************************************

_$SGDVLImpl _$$SGDVLImplFromJson(Map<String, dynamic> json) => _$SGDVLImpl(
      id: (json['id'] as num).toInt(),
      pgdTen: json['pgdTen'] as String,
      pgdNgay: json['pgdNgay'] as String,
      pgdGio: json['pgdGio'] as String,
      pgdDiadiem: json['pgdDiadiem'] as String,
      displayOrder: (json['displayOrder'] as num).toInt(),
      createdDate: json['createdDate'] as String,
      createdBy: json['createdBy'] as String,
      modifiredDate: json['modifiredDate'] as String,
      modifiredBy: json['modifiredBy'] as String,
      duyet: json['duyet'] as bool,
      nguoiduyet: json['nguoiduyet'] as String,
      status: json['status'] as bool,
      tongsoDndk: (json['tongsoDndk'] as num).toInt(),
      soDnPhongvan: (json['soDnPhongvan'] as num).toInt(),
      soDnUyquyenPv: (json['soDnUyquyenPv'] as num).toInt(),
      tongNhucauTd: (json['tongNhucauTd'] as num).toInt(),
      nhucautrongtinh: (json['nhucautrongtinh'] as num).toInt(),
      nhucauNgoaitinh: (json['nhucauNgoaitinh'] as num).toInt(),
      nhucauNgoainuoc: (json['nhucauNgoainuoc'] as num).toInt(),
      nhucauTdldCotrinhdo: (json['nhucauTdldCotrinhdo'] as num).toInt(),
      nhucauTdpt: (json['nhucauTdpt'] as num).toInt(),
      soUvDangkyPgd: (json['soUvDangkyPgd'] as num).toInt(),
      soUvThamgiaPgd: (json['soUvThamgiaPgd'] as num).toInt(),
      soUvDuoctuvan: (json['soUvDuoctuvan'] as num).toInt(),
      soUvDuocPv: (json['soUvDuocPv'] as num).toInt(),
      soUvDatsotuyen: (json['soUvDatsotuyen'] as num?)?.toInt(),
      trongdoUvNu: (json['trongdoUvNu'] as num).toInt(),
      soLdCotrinhdoDatsotuyen: (json['soLdCotrinhdoDatsotuyen'] as num).toInt(),
      soLdptDatsotuyen: (json['soLdptDatsotuyen'] as num).toInt(),
      soLDhenphongvan: (json['soLDhenphongvan'] as num).toInt(),
      songuoiDkxkld: (json['songuoiDkxkld'] as num).toInt(),
      soketnoiThanhcong: json['soketnoiThanhcong'],
      ghichu: json['ghichu'] as String?,
      matinh: json['matinh'] as String,
    );

Map<String, dynamic> _$$SGDVLImplToJson(_$SGDVLImpl instance) =>
    <String, dynamic>{
      'id': instance.id,
      'pgdTen': instance.pgdTen,
      'pgdNgay': instance.pgdNgay,
      'pgdGio': instance.pgdGio,
      'pgdDiadiem': instance.pgdDiadiem,
      'displayOrder': instance.displayOrder,
      'createdDate': instance.createdDate,
      'createdBy': instance.createdBy,
      'modifiredDate': instance.modifiredDate,
      'modifiredBy': instance.modifiredBy,
      'duyet': instance.duyet,
      'nguoiduyet': instance.nguoiduyet,
      'status': instance.status,
      'tongsoDndk': instance.tongsoDndk,
      'soDnPhongvan': instance.soDnPhongvan,
      'soDnUyquyenPv': instance.soDnUyquyenPv,
      'tongNhucauTd': instance.tongNhucauTd,
      'nhucautrongtinh': instance.nhucautrongtinh,
      'nhucauNgoaitinh': instance.nhucauNgoaitinh,
      'nhucauNgoainuoc': instance.nhucauNgoainuoc,
      'nhucauTdldCotrinhdo': instance.nhucauTdldCotrinhdo,
      'nhucauTdpt': instance.nhucauTdpt,
      'soUvDangkyPgd': instance.soUvDangkyPgd,
      'soUvThamgiaPgd': instance.soUvThamgiaPgd,
      'soUvDuoctuvan': instance.soUvDuoctuvan,
      'soUvDuocPv': instance.soUvDuocPv,
      'soUvDatsotuyen': instance.soUvDatsotuyen,
      'trongdoUvNu': instance.trongdoUvNu,
      'soLdCotrinhdoDatsotuyen': instance.soLdCotrinhdoDatsotuyen,
      'soLdptDatsotuyen': instance.soLdptDatsotuyen,
      'soLDhenphongvan': instance.soLDhenphongvan,
      'songuoiDkxkld': instance.songuoiDkxkld,
      'soketnoiThanhcong': instance.soketnoiThanhcong,
      'ghichu': instance.ghichu,
      'matinh': instance.matinh,
    };
